# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        # - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        digits: 6
        enabled: true
        sender_email: grosfilrouge@gmail.com
        sender_name: Prends un cours et plus vite que ça !  # Optional
        template: security/2fa_login.html.twig
        # alternative_template: security/2fa_login_alternative.html.twig