2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa_check

# login_2fa:
#     path: /login/2fa
#     defaults: { _controller: App\Controller\SecurityController::login2FAAction }

# logout:
#     path: /logout
